import { PLAYER_START_MASS } from './physics'

export const FARM_BUILD_COST = PLAYER_START_MASS * 2.5
export const RANCH_BUILD_COST = PLAYER_START_MASS * 4
export const FARM_STRUCTURE_MASS = PLAYER_START_MASS * 1.8
export const RANCH_STRUCTURE_MASS = PLAYER_START_MASS * 2.8
export const AVATAR_INCUBATE_SEC = 3
export const AVATAR_SPAWN_INVINCIBLE_SEC = 3
export const FARM_PELLET_INTERVAL_SEC = 3
export const FARM_PELLET_RING_RADIUS = 130
export const FARM_PELLET_COUNT = 8
export const FARM_NEARBY_PELLET_CAP = 48
export const RANCH_ALLY_INTERVAL_SEC = 30
export const RANCH_SPAWN_RING_RADIUS = 200
export const AVATAR_INITIAL_PELLETS = 220
export const AVATAR_SPAWN_OFFSET = 90

/** @deprecated use FARM_BUILD_COST */
export const AVATAR_FARM_MASS_THRESHOLD = FARM_BUILD_COST
/** @deprecated use RANCH_BUILD_COST */
export const AVATAR_RANCH_MASS_THRESHOLD = RANCH_BUILD_COST
